services:
  - type: web
    name: grapes-farm-planner
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 10000
    plan: free
    python:
      version: 3.10.13
