services:
  - type: web
    name: grapes-farm-planner
    env: python
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 3
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    plan: free
    python:
      version: 3.10.12
