# Render Blueprint for Grapes Farm Planner
# Reference: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: grapes-farm-planner
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install gunicorn==20.1.0
      pip install -r requirements.txt
      mkdir -p models
      touch models/grape_model.h5
      touch models/apple_disease.h5
      touch models/grape_leaf_disease_model.h5
    startCommand: |
      python -m gunicorn.app.wsgiapp --bind :$PORT --workers 2 --threads 4 --worker-class gthread --timeout 120 app:app
    
    # Environment variables
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB
    
    # Resource allocation
    plan: free
    region: oregon
    
    # Health check
    healthCheckPath: /health
    autoDeploy: true
    
    # Required environment variables
    envVarsFrom:
      - envVar: MONGO_URI
        description: "MongoDB connection string"
        required: true
      - key: SECRET_KEY
        generateValue: true
      - envVar: WEATHER_API_KEY
        description: "OpenWeatherMap API key"
        required: true
      - envVar: GEMINI_API_KEY
        description: "Google Gemini API key"
        required: true
