# Render Blueprint for Grapes Farm Planner
# Using Docker deployment for better dependency management
services:
  - type: web
    name: grapes-farm-planner
    docker:
      dockerfile: Dockerfile
      dockerContext: .
    env: docker
    
    # Environment variables
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /app
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: UPLOAD_FOLDER
        value: /app/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB
    
    # Resource allocation
    plan: free
    region: oregon
    
    # Health check
    healthCheckPath: /health
    autoDeploy: true
    
    # Required environment variables
    envVarsFrom:
      - envVar: MONGO_URI
        description: "MongoDB connection string"
        required: true
      - envVar: SECRET_KEY
        generateValue: true
      - envVar: WEATHER_API_KEY
        description: "OpenWeatherMap API key"
        required: true
      - envVar: GEMINI_API_KEY
        description: "Google Gemini API key"
        required: true
