# Render Blueprint for Grapes Farm Planner
# Reference: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: grapes-farm-planner
    env: python
    python:
      version: 3.10.13
    
    # Environment variables
    envVars:
      # Application Settings
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
        
      # TensorFlow Settings
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
        
      # File Upload Settings
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"  # 16MB
    
    # Build and deployment settings
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers=2 --threads=4 --worker-class=gthread --bind :$PORT
    
    # Resource allocation (adjust based on your needs)
    plan: free  # Can be upgraded to 'standard' for production
    region: oregon  # Choose the region closest to your users
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy from Git
    autoDeploy: true
    
    # Environment variables that should be set in the Render dashboard
    envVarsFrom:
      - envVar: MONGO_URI
        description: "MongoDB connection string"
        required: true
      - envVar: WEATHER_API_KEY
        description: "OpenWeatherMap API key"
        required: true
      - envVar: GEMINI_API_KEY
        description: "Google Gemini API key"
        required: true
